version: '3'
services:
  web:
    build: .
    command: "bundle exec rails server -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - $HOME/.ssh:/root/.ssh
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - '.env'
    tmpfs:
      - /app/log
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - 443:443
    depends_on:
      - web
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - database-volume:/var/lib/mysql
volumes:
  database-volume:
