default: &default
  adapter:  mysql2
  encoding: utf8mb4
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host:     <%= ENV["MYSQL_HOSTNAME"] %>

development:
  <<: *default
  database: draft_manager_development

test:
  <<: *default
  database: draft_manager_test

production:
  <<: *default
  database: draft_manager_production
